version: '3.7'
services:
  discord:
    build: .
    container_name: zwerl-discord
    restart: always
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      - PORT=${PORT}
      - TOKEN=${TOKEN}
      - CLIENT_ID=${CLIENT_ID}
  postgres:
    image: postgres:12.2
    restart: always
    container_name: zwerl-postgres
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: