version: '3.7'
services:
  discord:
    image: ghcr.io/zwerl-project/discord-bot:main 
    container_name: zwerl-discord
    restart: always
    ports:
      - ${PORT}:${PORT}
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      - PORT=${PORT}
      - TOKEN=${TOKEN}
      - CLIENT_ID=${CLIENT_ID}
    depends_on:
      - postgres
  postgres:
    image: postgres:12.2
    restart: always
    container_name: zwerl-postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: