version: '3.7'
services:
  discord:
    build: .
    container_name: zwerl-discord
    restart: unless-stopped
    environment:
      - PORT=${PORT}
      - TOKEN=${TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
    expose:
      - ${PORT}:${PORT}
