version: '3.7'
services:
  discord:
    build: .
    container_name: zwerl-discord
    restart: always
    ports:
      - ${PORT}:${PORT}
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - TOKEN=${TOKEN}
      - CLIENT_ID=${CLIENT_ID}
    networks:
      - zwerl-net